Fri Feb 06 11:32:46 CET 2015 : Server di rete Apache Derby: 10.10.1.3 - (1557168) avviato e pronto ad accettare connessioni sulla porta 1527
----------------------------------------------------------------
Fri Feb 06 11:32:46 CET 2015:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): istanza a816c00e-014b-5e72-f154-00001d49406b
sulla directory di database D:\Documents\Dropbox\Università\2 - Laurea Triennale\3 - Terzo anno\Esami da sostenere\Sviluppo applicazioni software\Progetto\Git\UniSvilAppSoft\CryptoHelperDB con caricatore classi sun.misc.Launcher$AppClassLoader@1d44bcfa 
Caricato da file:/C:/Program%20Files/Java/jdk1.8.0_25/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_25-b18
user.dir=C:\Program Files\Java\jdk1.8.0_25\db
os.name=Windows 8.1
os.arch=amd64
<<<<<<< HEAD
os.version=6.3
derby.system.home=C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Fri Feb 06 12:21:22 CET 2015: arresto in corso del motore di Derby
----------------------------------------------------------------
Fri Feb 06 12:21:22 CET 2015:
Arresto dell'istanza a816c00e-014b-5e4c-31d2-00006960ef3f nella directory del database C:\Users\Federica\Documents\NetBeansProjects\UniSvilAppSoft\CryptoHelperDB con il caricatore di classi sun.misc.Launcher$AppClassLoader@1d44bcfa 
----------------------------------------------------------------
=======
os.version=6.3
derby.system.home=D:\Documents\Dropbox\Università\2 - Laurea Triennale\3 - Terzo anno\Esami da sostenere\Sviluppo applicazioni software\Progetto\Git\UniSvilAppSoft
Programma di caricamento classe database avviato - derby.database.classpath=''
Fri Feb 06 11:32:48 CET 2015 Thread[DRDAConnThread_2,5,main] (XID = 4047), (SESSIONID = 0), (DATABASE = CryptoHelperDB), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri Feb 06 11:32:48 CET 2015 Thread[DRDAConnThread_2,5,main] (DATABASE = CryptoHelperDB), (DRDAID = {1}), Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
>>>>>>> 30437d80033f06f5387c354e4636cca561ecd360
